name: svdk-regression
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch>=1.9.0
  - torchvision>=0.10.0
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scipy>=1.7.0
  - scikit-learn>=1.0.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - plotly>=5.0.0
  - tqdm>=4.62.0
  - pip
  - pip:
    - gpytorch>=1.6.0
